MONGODB_HOST: mongodb-{{ env }}.nirfaws.online
REDIS_HOST: redis-{{ env }}.nirfaws.online
MYSQL_HOST: mysql-{{ env }}.nirfaws.online 
RABBITMQ_HOST: rabbitmq-{{ env }}.nirfaws.online 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.nirfaws.online
USER_HOST: user.backend-alb-{{ env }}.nirfaws.online
CART_HOST: cart.backend-alb-{{ env }}.nirfaws.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.nirfaws.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.nirfaws.online
